import { StoredProvider } from './types';

// List of supported Gemini models
const DEFAULT_GEMINI_MODELS = [
    {
        name: 'gemini-2.0-flash-exp',
        displayName: 'Gemini 2.0 Flash Experimental'
    },
    {
        name: 'gemini-1.5-flash',
        displayName: 'Gemini 1.5 Flash'
    },
    {
        name: 'gemini-1.5-flash-8b',
        displayName: 'Gemini 1.5 Flash 8B'
    },
    {
        name: 'gemini-1.5-pro',
        displayName: 'Gemini 1.5 Pro'
    }
];

const DEFAULT_OPENAI_MODELS = [
    {
        name: 'gpt-3.5-turbo',
        displayName: 'GPT-3.5 Turbo'
    },
    {
        name: 'gpt-4',
        displayName: 'GPT-4'
    },
    {
        name: 'gpt-4-turbo',
        displayName: 'GPT-4 Turbo'
    }
];

const DEFAULT_ANTHROPIC_MODELS = [
    {
        name: 'claude-3-opus',
        displayName: 'Claude 3 Opus'
    },
    {
        name: 'claude-3-sonnet',
        displayName: 'Claude 3 Sonnet'
    },
    {
        name: 'claude-3-haiku',
        displayName: 'Claude 3 Haiku '
    }
];

export const DEFAULT_SELECTED_MODEL = 'Gemini:gemini-1.5-pro';

export const DEFAULT_PROVIDERS: StoredProvider[] = [
    {
        name: 'Gemini',
        type: 'gemini',
        apiKey: '',
        verified: false,
        models: DEFAULT_GEMINI_MODELS
    },
    {
        name: 'OpenAI',
        type: 'openai',
        apiKey: '',
        verified: false,
        models: DEFAULT_OPENAI_MODELS
    },
    {
        name: 'Anthropic',
        type: 'anthropic',
        apiKey: '',
        verified: false,
        models: DEFAULT_ANTHROPIC_MODELS
    }
] as const;

// Default prompt for video analysis
export const DEFAULT_PROMPT = `You are a specialized assistant for creating comprehensive video summaries from subtitles. The subtitles have been automatically generated by YouTube and may contain transcription errors, especially with technical terms, software names, and specialized vocabulary.

## Task

Create a concise yet comprehensive summary of the video based on the provided subtitles.

## Handling Transcription Errors

- Correct obvious transcription errors based on context and your domain knowledge
- Pay special attention to technical terms, software names, programming languages, and IDE plugins which are frequently misrecognized
- If multiple interpretations are possible, choose the most likely one based on the video's context

## Output Structure

` + "```" + `
## Summary
[Write a comprehensive summary of the main topic and key message]

## Key points
- [Key point 1]
- [Key point 2]
- [Additional key points...]

## Technical terms
- **[[Term 1]]**: [Explanation of term 1]
- **[[Term 2]]**: [Explanation of term 2]
- [Additional terms as needed...]

## Conclusion
[Write a brief conclusion]
` + "```" + `

Note: Include all sections. If there are no technical terms, omit that section entirely.`;

export const DEFAULT_MAX_TOKENS = 3000;
export const DEFAULT_TEMPERATURE = 1;